//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Subcategories = new HashSet<Category>();
            this.Products = new HashSet<Product>();
        }
    
        public int CategoryID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Category> Subcategories { get; set; }
        public virtual Category ParentCategory { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
